name: Integration
on:
  push: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/download-release-action@master
      with:
        release: 1
    - name: Check release tag name folder exists
      run: |
        [ -d "integration-test-tag" ]
    - name: Check assets exist inside the release folder
      run: |
        [ -f "integration-test-tag/a.zip" ]
        [ -f "integration-test-tag/b.zip" ]
